server:
  port: 8082
  servlet:
    context-path: /oauth-client-spring
  tomcat:
    max-connections: 8192
    accept-count: 100

spring:
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: newClient
            client-secret: newClientSecret
            scope: read,write,openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/oauth-client-spring/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/auth
            token-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/token
            user-info-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
            issuer-uri: http://localhost:8083/auth/realms/baeldung
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false

app:
  security:
    oauth2:
      client:
        logout:
            redirect-uri: http://localhost:8082/oauth-client-spring
    cors:
      client:
        origin: http://localhost:8082

resourceserver:
  api:
    foo:
      url: http://localhost:8081/resource-server/api/foos

logging:
  level:
    org.springframework: INFO
    org.springframework.security: TRACE
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, metrics
    access:
      default: none
  endpoint:
    health:
      access: read-only
    info:
      access: read-only
    beans:
      access: read-only
    metrics:
      access: read-only
