spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            redirect-uri: https://oauth-spring-client-bruno-stuessi-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/oauth-client-spring/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: https://oauth-authorization-server-bruno-stuessi-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/auth/realms/baeldung/protocol/openid-connect/auth
            token-uri: https://oauth-authorization-server-bruno-stuessi-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/auth/realms/baeldung/protocol/openid-connect/token
            user-info-uri: https://oauth-authorization-server-bruno-stuessi-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/auth/realms/baeldung/protocol/openid-connect/userinfo
            jwk-set-uri: https://oauth-authorization-server-bruno-stuessi-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/auth/realms/baeldung/protocol/openid-connect/certs
            issuer-uri: https://oauth-authorization-server-bruno-stuessi-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/auth/realms/baeldung

app:
  security:
    oauth2:
      client:
        logout:
          redirect-uri: https://oauth-spring-client-bruno-stuessi-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/oauth-client-spring
    cors:
      client:
        origin: https://oauth-spring-client-bruno-stuessi-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com

resourceserver:
  api:
    foo:
      url: https://oauth-resource-server-bruno-stuessi-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/resource-server/api/foos

logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    reactor.netty.http.client: INFO